### ISSUE TITLE
Don't change sprites to biggest value (or add option to disable)

### ISSUE THREAD

**Issue by Purpzie** [dbeckwith/factorio-infinite-resources#1]
https://github.com/dbeckwith/factorio-infinite-resources/blob/98eaed05d2df179db227c35c8b14f71d6c1ab46f/data-final-fixes.lua#L13-L18

While this gives players an indication that the resource is infinite, this also makes ores look less normal in general, especially around the edges. Apologies if this is somehow not possible - it seems as easy as just removing this bit of code - but I've never written in Lua, nor have I modded Factorio before.

**Comment by dbeckwith** [comment]
Unfortunately I believe the visual size of each ore sprite is tied to its amount. Since the way this mod works is by modifying the allowed ranges of amounts of resources to be between 100% and 100%, all ores spawn with the same amount, so they have the same sprite size. Because every ore spawns with a value of "100", which is treated as a "low number", they end up showing the smallest visual sprite size. The code you linked makes it so the largest sprite is shown instead of it always being the smallest, which I thought better reflected the infinite capacity of the ore.

**Comment by Purpzie** [comment]
Ahh, okay. Thank you for explaining!
